/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\roomModel.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/roomModel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Cube320" geometry={nodes.Cube320.geometry} material={nodes.Cube320.material} position={[4.867, 3.146, -0.53]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/roomModel.glb')
