/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Room.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Room.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Empty012" position={[0.812, 1.305, -1.533]} rotation={[0, -1.455, 0]}>
        <mesh name="Cube318" geometry={nodes.Cube318.geometry} material={nodes.Cube318.material} position={[-0.68, 0.119, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
      </group>
      <mesh name="Cube320" geometry={nodes.Cube320.geometry} material={nodes.Cube320.material} position={[4.867, 3.146, -0.53]} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/Room.gltf')
